//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportDataBib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPS_DMD_COLLECTION
    {
        public int COLLECTION_ID { get; set; }
        public Nullable<int> PARENT_COLLECTION_ID { get; set; }
        public string COLLECTION_VI_TITLE { get; set; }
        public string COLLECTION_EN_TITLE { get; set; }
        public string MDTYPE { get; set; }
        public string TEMPLATE_NAME { get; set; }
        public string EDITOR_NAME { get; set; }
        public string IMAGE_URL { get; set; }
        public int MENU_ID { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public short RECORD_ACCESS_LEVEL { get; set; }
        public short RECORD_STATUS { get; set; }
        public short RECORD_VERSION { get; set; }
        public string RECORD_CREATOR { get; set; }
        public System.DateTime RECORD_CREATED_DATE { get; set; }
        public string RECORD_MODIFIER { get; set; }
        public Nullable<System.DateTime> RECORD_MODIFIED_DATE { get; set; }
    }
}
