//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportDataBib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPS_DMD
    {
        public int DMD_ID { get; set; }
        public int PARENT_DMD_ID { get; set; }
        public int COLLECTION_ID { get; set; }
        public string DMD_OBJID { get; set; }
        public string L05 { get; set; }
        public string L06 { get; set; }
        public string L07 { get; set; }
        public Nullable<short> F8_DATE1 { get; set; }
        public Nullable<short> F8_DATE2 { get; set; }
        public string F8_PUBPLACE { get; set; }
        public string F8_LANGUAGE { get; set; }
        public string ISBN_ISSN { get; set; }
        public Nullable<short> CALL_NUMBER_TAG { get; set; }
        public string CALL_NUMBER { get; set; }
        public string EDITION { get; set; }
        public string PUBLISHER { get; set; }
        public Nullable<short> LABEL_TAG { get; set; }
        public string LABEL { get; set; }
        public string MDTYPE { get; set; }
        public string XMLDATA { get; set; }
        public Nullable<int> ITEM_COUNT { get; set; }
        public Nullable<int> ITEM_HIT_COUNT { get; set; }
        public Nullable<int> METS_COUNT { get; set; }
        public Nullable<int> METS_HIT_COUNT { get; set; }
        public Nullable<bool> IS_INDEX { get; set; }
        public short RECORD_ACCESS_LEVEL { get; set; }
        public short RECORD_STATUS { get; set; }
        public short RECORD_VERSION { get; set; }
        public string RECORD_CREATOR { get; set; }
        public System.DateTime RECORD_CREATED_DATE { get; set; }
        public string RECORD_MODIFIER { get; set; }
        public Nullable<System.DateTime> RECORD_MODIFIED_DATE { get; set; }
        public string ITEM_LOCATION_SUMMARY { get; set; }
    }
}
